language: ruby
cache: bundler
rvm:
- 2.5

before_install:
- docker-compose -f spec/docker-compose.yml up -d --build

script:
- bundle exec rubocop
- bundle exec rake spec

notifications:
  email: false
